### ISSUE TITLE
Installation via Lazy.nvim?

### ISSUE THREAD

**Issue by drusmanbashir** [stsewd/isort.nvim#16]
I installed this via lazy  using:
  { "stsewd/isort.nvim", build = ":UpdateRemotePlugins" },

but the Isort command is not available to me. Can you help?

**Comment by stsewd** [comment]
Hi. Do you have the Python provider installed? You can check by running `:checkhealth` (search for Python 3 provider). You can also get more info about any possible issue by running `:UpdateRemotePlugins` manually.

**Comment by drusmanbashir** [comment]
Thanks i am using lsp provided isort.
