### ISSUE TITLE
Isort does not turn on. Error

### ISSUE THREAD

**Issue by Barmaley0** [stsewd/isort.nvim#17]
Sorting and management does not occur. A formatter error occurs. What could be the problem? Below I provide screenshots of the errors that occur. Errors do not appear immediately, but only when you start changing and saving the file; Mason does not generate errors.
My config:
neovim 0.9.5
Windows 10
Lazy.nvim
![image](https://github.com/stsewd/isort.nvim/assets/133758633/28b19bfb-682c-455b-bfe3-621e1927c732)

![image](https://github.com/stsewd/isort.nvim/assets/133758633/d426a26d-3acc-44c9-bf0f-89f996f38823)
Checkhealth
![image](https://github.com/stsewd/isort.nvim/assets/133758633/2f39ddea-22e2-444b-8619-fcc990b591b8)

**Comment by stsewd** [comment]
Hi, don't think this is a problem from this plugin, looks like you are using an LSP integration, and not this plugin.

**Comment by Barmaley0** [comment]
I understand. Perhaps someone has encountered this anyway?

**Comment by stsewd** [comment]
Probably the isort version you are using isn't compatible with the LSP/linter plugin you are using. I'm closing this issue since isn't a problem with this plugin.
