### ISSUE TITLE
Dropping last item causes mis-deleting of the last line in buffer in latest isort.

### ISSUE THREAD

**Issue by cjsoft** [stsewd/isort.nvim#9]
https://github.com/stsewd/isort.nvim/blob/2b0702e50ff8fdd915468f3f8c7b22f1a344625f/rplugin/python3/isort_nvim.py#L35

Seems latest isort (5.6.4) won't output an extra blank line. Dropping last item in this list will mis-deleting the last line in buffer, which is an unwanted behavior (Which deleted several lines of my code, QAQ). 

Maybe we can place a WARNING in README.md to let the user to make manual edit to adapt to their own isort version.

**Comment by stsewd** [comment]
I'm fine making this the default and mention to use the latest version of isort. Sorry for the late reply! PR is welcome!
